/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.trabajo5_friends;
import java.io.File;
import java.io.IOException;
import java.io.RandomAccessFile;
import java.lang.NumberFormatException;
import javax.swing.JOptionPane;
/**
 *
 * @author MacBook
 */
public class Principal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Principal.class.getName());

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnCreate = new javax.swing.JButton();
        btnRead = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        txtName = new javax.swing.JTextField();
        txtNumber = new javax.swing.JTextField();
        btnClear = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Name:");

        jLabel2.setText("Number:");

        btnCreate.setText("Create");
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });

        btnRead.setText("Search");
        btnRead.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReadActionPerformed(evt);
            }
        });

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });

        txtNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumberActionPerformed(evt);
            }
        });

        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(btnCreate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnRead)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnUpdate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnDelete))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(152, 152, 152)
                        .addComponent(btnClear))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(59, 59, 59)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNumber)
                            .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCreate)
                    .addComponent(btnRead)
                    .addComponent(btnUpdate)
                    .addComponent(btnDelete))
                .addGap(18, 18, 18)
                .addComponent(btnClear)
                .addContainerGap(55, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        try {
            String updateName = String.valueOf(txtName.getText());
            long newNumber = Long.parseLong(txtNumber.getText());
            
            String nameNumberString;
            String name;
            long number;
            int index;
            
            File file = new File("/Users/MacBook/Documents/POO/Trabajo5/friendsContact.txt");
            
            if (file.exists()==false) {
                file.createNewFile();
            }
            
            RandomAccessFile raf = new RandomAccessFile(file, "rw");
            boolean found = false;
            
            while (raf.getFilePointer() < raf.length()) {
                nameNumberString = raf.readLine();
                String[] lineSplit = nameNumberString.split("!");
                
                name = lineSplit[0];
                number = Long.parseLong(lineSplit[1]);
                
                if (name.equals(updateName)) {
                    found = true;
                    break;
                }
            }
            
            if (found == true) {
                File tmpFile = new File("/Users/MacBook/Documents/POO/Trabajo5/temp.txt");
                
                RandomAccessFile tmpraf = new RandomAccessFile(tmpFile, "rw");
                
                raf.seek(0);
                
                while (raf.getFilePointer() < raf.length()) {
                    nameNumberString = raf.readLine();
                    
                    index = nameNumberString.indexOf("!");
                    name = nameNumberString.substring(0, index);
                    
                    if (name.equals(updateName)) {
                        nameNumberString = name + "!" + String.valueOf(newNumber);
                        continue;
                    }
                    
                    tmpraf.writeBytes(nameNumberString);
                    tmpraf.writeBytes(System.lineSeparator());
                    break;
                }
                
                raf.seek(0);
                tmpraf.seek(0);
                
                while (tmpraf.getFilePointer() < tmpraf.length()) {
                    raf.writeBytes(tmpraf.readLine());
                    raf.writeBytes(System.lineSeparator());
                    break;
                }
                
                raf.setLength(tmpraf.length());
                
                tmpraf.close();
                raf.close();
                
                tmpFile.delete();
                
                JOptionPane.showMessageDialog(null, "The name was updated.");

            }
            
            else {
                raf.close();
                JOptionPane.showMessageDialog(null, "The name you want to update does not exist.");
            
            }    
        }
        
        catch (IOException ioe) {
            JOptionPane.showMessageDialog(null, "An error has occurred creating or opening the file. ");
        }
        catch (NumberFormatException nef) {
            JOptionPane.showMessageDialog(null, "A number format error has occurred.");
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
        try{
            String newName = String.valueOf(txtName.getText());
            long newNumber = Long.parseLong(txtNumber.getText());
            
            String nameNumberString;
            String name;
            long number;
         
            
            File file = new File("/Users/MacBook/Documents/POO/Trabajo5/friendsContact.txt");
            
            if (file.exists()==false) {
                file.createNewFile();
            }
            
            RandomAccessFile raf = new RandomAccessFile(file, "rw");
            boolean found = false;
            
            while (raf.getFilePointer() < raf.length()) {
                nameNumberString = raf.readLine();
                String[] lineSplit = nameNumberString.split("!");
                name = lineSplit[0];
                number = Long.parseLong(lineSplit[1]);
                
                if (name.equals(newName)|| number == newNumber) {
                    found = true;
                    break;
                }
            }
            
            if (found == false){
                nameNumberString = newName + "!" + String.valueOf(newNumber);
                raf.writeBytes(nameNumberString);
                raf.writeBytes(System.lineSeparator());
                JOptionPane.showMessageDialog(null, "Friend added.");
                txtName.setText("");
                txtNumber.setText("");
                raf.close();
            }
            
            else {
                raf.close();
                JOptionPane.showMessageDialog(null, "Friend name already exists.");
                txtName.setText("");
                txtNumber.setText("");
            } 
        }
        
        catch (IOException ioe) {
            JOptionPane.showMessageDialog(null, "An error has occurred creating or opening the file. ");
            txtName.setText("");
            txtNumber.setText("");
        }
        catch (NumberFormatException nef) {
            JOptionPane.showMessageDialog(null, "A number format error has occurred.");
            txtName.setText("");
            txtNumber.setText("");
        }
    }//GEN-LAST:event_btnCreateActionPerformed

    private void txtNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumberActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        txtName.setText("");
        txtNumber.setText("");
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnReadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReadActionPerformed
        try{
            String nameNumberString;
            String name;
            String searchName = String.valueOf(txtName.getText());
            
            long number;
            
            File file = new File("/Users/MacBook/Documents/POO/Trabajo5/friendsContact.txt");
            
            if (file.exists()==false) {
                file.createNewFile();
            }
            
            RandomAccessFile raf = new RandomAccessFile(file, "rw");
            boolean found = false;
            
            while (raf.getFilePointer() < raf.length()) {
                nameNumberString = raf.readLine();
                String[] lineSplit = nameNumberString.split("!");
                
                name = lineSplit[0];
                number = Long.parseLong(lineSplit[1]);
                
                if (name.equals(searchName)) {
                    txtName.setText(String.valueOf(name));
                    txtNumber.setText(String.valueOf(number));
                    found = true;
                    raf.close();
                    JOptionPane.showMessageDialog(null, "The name was found.");
                    break;
                }
            }
            
            if (found == false) {
                JOptionPane.showMessageDialog(null, "The name not was found");
                txtName.setText("");
                txtNumber.setText("");
                raf.close();
            }
            
        }
        catch (IOException ioe) {
            JOptionPane.showMessageDialog(null, "An error has occurred creating or opening the file. ");
        }
        catch (NumberFormatException nef) {
            JOptionPane.showMessageDialog(null, "A number format error has occurred");
        }
    }//GEN-LAST:event_btnReadActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        try {
            String deleteName = String.valueOf(txtName.getText());
            
            String nameNumberString;
            String name;
            long number;
            int index;
            
            File file = new File("/Users/MacBook/Documents/POO/Trabajo5/friendsContact.txt");
            
            if (file.exists()==false) {
                file.createNewFile();
            }
            
            RandomAccessFile raf = new RandomAccessFile(file, "rw");
            boolean found = false;
            
            while (raf.getFilePointer() < raf.length()) {
                nameNumberString = raf.readLine();
                String[] lineSplit = nameNumberString.split("!");
                
                name = lineSplit[0];
                number = Long.parseLong(lineSplit[1]);
                
                if (name.equals(deleteName)) {
                    found = true;
                    break;
                }
            }
            
            if (found == true) {
                File tmpFile = new File("/Users/MacBook/Documents/POO/Trabajo5/temp.txt");
                
                RandomAccessFile tmpraf = new RandomAccessFile(tmpFile, "rw");
                
                raf.seek(0);
                
                while (raf.getFilePointer() < raf.length()) {
                    nameNumberString = raf.readLine();
                    
                    index = nameNumberString.indexOf("!");
                    name = nameNumberString.substring(0, index);
                    
                    if (name.equals(deleteName)) {
                        continue;
                    }
                    
                    tmpraf.writeBytes(nameNumberString);
                    tmpraf.writeBytes(System.lineSeparator());
                    break;
                }
                
                raf.seek(0);
                tmpraf.seek(0);
                
                while (tmpraf.getFilePointer() < tmpraf.length()) {
                    raf.writeBytes(tmpraf.readLine());
                    raf.writeBytes(System.lineSeparator());
                    break;
                }
                
                raf.setLength(tmpraf.length());
                
                tmpraf.close();
                raf.close();
                
                tmpFile.delete();
                
                JOptionPane.showMessageDialog(null, "The name was deleted.");
                
               
            }
            
            else {
                raf.close();
                JOptionPane.showMessageDialog(null, "The name you want to delete does not exist.");
            
            }    
        }
        
        catch (IOException ioe) {
            JOptionPane.showMessageDialog(null, "An error has occurred creating or opening the file. ");
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Principal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnCreate;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnRead;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtNumber;
    // End of variables declaration//GEN-END:variables
}
